export class AppAction {
  static AUTH = {
    LOADING: "LOGGING USER",
    SUCCESS: "USER LOGIN SUCCESS",
    FAILURE: "USER LOGIN FAILED",
  };

  static AUTH_REVOKE = {
    LOADING: "SIGNING OUT",
    SUCCESS: "SIGNOUT SUCCESSFULLY",
    FAILURE: "ERROR IN SIGNOUT",
  };
  static REGISTER = {
    LOADING: "REGISTERING USER",
    SUCCESS: "REGISTRATION SUCCESS",
    FAILURE: "REGISTRATION FAILED",
  };
  static BLOGS = {
    LOADING: "LOADING BLOGS",
    SUCCESS: "BLOGS LOADED",
    FAILURE: "BLOGS LOAD FAILED",
  };
  static BLOG = {
    LOADING: "LOADING BLOG",
    SUCCESS: "BLOG LOADED",
    FAILURE: "BLOG LOAD FAILED",
  };

  static FETCH_USER_DETAILS = {
    LOADING: "FETCHING USER DETAILS",
    SUCCESS: "USER DETAILS FETCHED",
    FAILURE: "ERROR IN FETCHING USER DETAILS",
  };

  static CREATE_BLOG = {
    LOADING: "SAVING BLOG",
    SUCCESS: "BLOG SAVED",
    FAILURE: "ERROR IN SAVING BLOG",
    RESET: "RESET BLOG CREATE",
  };

  static APPLICATION_LOG = {
    SAVING: "SAVING APPLICATION LOG",
    SAVED: "APPLICATION LOG SAVED",
    FAILURE: "ERROR IN SAVING BLOG",
  };

  static BLOG_LIKED = {
    SAVING: "LIKING BLOG",
    SAVED: "BLOG LIKED SUCCESSFULLY",
    FAILURE: "ERROR IN LIKING BLOG",
  };

  static BLOG_DETAILS = {
    LOADING: "LOADING BLOG DETAILS",
    LOADED: "BLOG DETAILS LOADED SUCCESSFULLY",
    FAILURE: "ERROR IN LOADING BLOG DETAILS",
  };

  static TOAST_MESSAGE = {
    SHOW: "SHOW TOAST MESSAGE",
    HIDE: "HIDE TOAST MESSAGE",
  };

  static FETCH_COMMENT = {
    LOADING: "FETCHING COMMENT DETAILS",
    LOADED: "COMMENT DETAILS FETCHED SUCCESSFULLY",
    FAILURE: "ERROR IN LOADING COMMENT DETAILS",
  };

  static ADD_COMMENT = {
    SAVING: "SAVING COMMENT DETAILS",
    SAVED: "COMMENT SAVED SUCCESSFULLY",
    FAILURE: "ERROR IN SAVING COMMENT",
    RESET: "RESET COMMENT ADD STATUS",
  };

  static ACTIVE_APP = {
    SET_ACTIVE_APP: "SET ACTIVE APP",
  };

  static ADD_TRADE = {
    SAVING: "SAVING TRADE DETAILS",
    SAVED: "TRADE DETAILS SAVED SUCCESSFULLY",
    FAILURE: "ERROR IN SAVING TRADE",
  };

  static FETCH_TRADES = {
    LOADING: "FETCHING TRADES",
    SUCCESS: "TRADES FETCHED SUCCESSFULLY",
    FAILURE: "ERROR IN FETCHING TRADES",
  };

  static FETCH_PRODUCTS = {
    LOADING: "FETCHING PRODUCTS",
    SUCCESS: "PRODUCTs FETCHED SUCCESSFULLY",
    FAILURE: "ERROR IN FETCHING PRODUCTS",
  };

  static ADD_PRODUCT = {
    SAVING: "ADDING PRODUCTS",
    SAVED: "PRODUCT ADDED SUCCESSFULLY",
    FAILURE: "ERROR IN PRODUCT ADDITION",
    RESET: "RESET PRODUCT SAVE",
  };

  static TAGS = {
    SAVING: "SAVING TAGS",
    SAVED: "TAGS SAVED SUCCESSFULLY",
    FAILURE: "ERROR IN SAVING TAGS",
    RESET: "RESET TAG ADDITION",
  };

  static REMOVE_TAG = {
    SAVING: "REMOVING TAGS",
    SAVED: "TAGS REMOVED SUCCESSFULLY",
    FAILURE: "ERROR IN REMOVED TAGS",
    RESET: "RESET TAG REMOVE",
  };

  static GET_TAGS = {
    LOADING: "FETCHING TAGS",
    LOADED: "LOADED TAGS",
    FAILURE: "ERROR IN LOADING TAGS",
  };

  static ADD_TO_CART_OR_WISH = {
    SAVING: "ADDING TO CART OR WISH",
    SAVED: "ADDED TO CART OR WISH",
    FAILURE: "FAILURE TO ADD PRODUCT TO CART OR WISH",
  };

  static SELECT_TAG = "SELECT_TAG";

  static CART_ITEMS = {
    LOADING: "LOADING CART ITEMS",
    LOADED: "LOADED CART ITEMS",
    FAILURE: "FAILURE TO LOAD CART ITEMS",
  };

  static LOADER = {
    SHOW: "SHOW LOADING SPINNER",
    HIDE: "HIDE LOADING SPINNER",
  };

  static CART_SUMMARY = {
    LOADING: "LOADING CART SUMMARY",
    LOADED: "CART SUMMARY",
    FAILURE: "FAILURE TO LOAD CART SUMMARY",
  };

  static QUANTITY_UPDATE = {
    SAVING: "UPDATING CART ITEM QUANTITY",
    SAVED: "CART ITEM QUANTITY UPDATE SUCCESSFULLY",
    FAILURE: "FAILURE TO UPDATE CART QUANTITY",
  };

  static REMOVE_CART_ITEM = {
    SAVING: "REMOVING ITEM FROM CART",
    SAVED: "CART ITEM REMOVED SUCCESSFULLY",
    FAILURE: "FAILURE TO REMOVE CART ITEM",
  };

  static USER_PROFILE = {
    SAVING: "SAVING USER PROFILE",
    SAVED: "SAVED USER PROFILE SUCCESSFULLY",
    FAILURE: "FAILURE TO SAVE USER PROFILE",
    RESET: "RESET USER PROFILE",
  };

  static ADDRESS = {
    SAVING: "SAVING USER ADDRESS",
    SAVED: "SAVED USER ADDRESS SUCCESSFULLY",
    FAILURE: "FAILURE TO SAVE USER ADDRESS",
    RESET: "RESET ADDRESS",
  };

  static PROFILE = {
    LOADING: "LOADING USER PROFILE",
    LOADED: "USER PROFILE LOADED SUCCESSFULLY",
    FAILURE: "FAILURE TO LOAD USER PROFILE",
  };

  static DELETE_ADDRESS = {
    SAVING: "DELETING USER ADDRESS",
    SAVED: "USER ADDRESS DELETED SUCCESSFULLy",
    FAILURE: "FAILURE TO DELETE USER ADDRESS",
  };

  static CHANGE_PASSWORD = {
    SAVING: "CHANGING PASSWORD",
    SAVED: "PASSWORD CHANGED SUCCESSFULLY",
    FAILURE: "ERROR IN CHANGING PASSWORD",
  };
}
